name: env-fuzzycorr
channels:
  - conda-forge
dependencies:
  - python=3.6
  - geopandas
  - gdal
  - rasterio
  - numpy
  - pandas
  - alphashape
  - mapclassify
  - pathlib
  - pyproj
  - scipy
  - earthpy
  - matplotlib
