name: env-valitools
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - geopandas
  - ogr
  - gdal
  - rasterio
  - numpy
  - pandas
  - alphashape
  - mapclassify
  - pathlib
  - pyproj
  - scipy
  - pykrige
  - sys

